default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: safe-walk_development

test:
  <<: *default
  database: safe-walk_test

production:
  <<: *default
  database: safe-walk_production
  username: safe-walk
  password: <%= ENV['SAFE-WALK_DATABASE_PASSWORD'] %>
